version: '3.8'

services:
  gowebly_fiber:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      BACKEND_PORT: 8080
    networks:
      - gowebly_fiber_network
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - gowebly_fiber_network

networks:
  gowebly_fiber_network:
