version: '3.8'

services:
  gowebly_fiber:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '7000:7000'
    environment:
      BACKEND_PORT: 7000
    networks:
      - gowebly_fiber_network

networks:
  gowebly_fiber_network:
